"""changed back to id on posts

Revision ID: 1b4561869a00
Revises: c1b97c80b385
Create Date: 2023-10-02 15:52:35.450097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4561869a00'
down_revision = 'c1b97c80b385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_plant_plants', type_='foreignkey')
        batch_op.drop_constraint('fk_posts_user_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_users'), 'users', ['user'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_posts_plant_plants'), 'plants', ['plant'], ['id'])

    with op.batch_alter_table('user_plant', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('plant_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_constraint('fk_user_plant_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_user_plant_plant_id_plants', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_plant_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_plant_plant_id_plants'), 'plants', ['plant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_plant_plant_id_plants'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_plant_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_plant_plant_id_plants', 'plants', ['plant_id'], ['common_name'])
        batch_op.create_foreign_key('fk_user_plant_user_id_users', 'users', ['user_id'], ['username'])
        batch_op.alter_column('plant_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_plant_plants'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_posts_user_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_user_users', 'users', ['user'], ['username'])
        batch_op.create_foreign_key('fk_posts_plant_plants', 'plants', ['plant'], ['common_name'])

    # ### end Alembic commands ###
