"""added plant and post relationship

Revision ID: 6724d07f6337
Revises: dc12d1f29481
Create Date: 2023-09-22 18:07:39.265448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6724d07f6337'
down_revision = 'dc12d1f29481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('plant', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_posts_plant_id_plants', type_='foreignkey')
        batch_op.drop_constraint('fk_posts_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_plant_plants'), 'plants', ['plant'], ['common_name'])
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_users'), 'users', ['user'], ['username'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('plant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_posts_user_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_posts_plant_plants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_user_id_users', 'users', ['user_id'], ['username'])
        batch_op.create_foreign_key('fk_posts_plant_id_plants', 'plants', ['plant_id'], ['common_name'])
        batch_op.drop_column('plant')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
