"""testing relationship

Revision ID: 749e343bce7a
Revises: 26c1873d8fb4
Create Date: 2023-09-23 09:48:49.482414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749e343bce7a'
down_revision = '26c1873d8fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('plant',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_constraint('fk_posts_plant_plants', type_='foreignkey')
        batch_op.drop_constraint('fk_posts_user_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_plant_plants'), 'plants', ['plant'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_users'), 'users', ['user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_user_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_posts_plant_plants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_user_users', 'users', ['user'], ['username'])
        batch_op.create_foreign_key('fk_posts_plant_plants', 'plants', ['plant'], ['common_name'])
        batch_op.alter_column('plant',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('user',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
