"""bringing back id

Revision ID: 7eb58a03f703
Revises: ad38111d6a25
Create Date: 2023-09-26 11:47:16.364749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb58a03f703'
down_revision = 'ad38111d6a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plant', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_plant_plant_plants', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_plant_plant_plants'), 'plants', ['plant'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_plant_plant_plants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_plant_plant_plants', 'plants', ['plant'], ['common_name'])

    # ### end Alembic commands ###
