"""added signup

Revision ID: 9f6b345f92e7
Revises: d59cedbfda1f
Create Date: 2023-09-13 11:38:11.462008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6b345f92e7'
down_revision = 'd59cedbfda1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('accountType')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accountType', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
