"""changed up relationship columns user and post

Revision ID: ac5790e76d13
Revises: 
Create Date: 2023-10-08 21:41:13.668700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5790e76d13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_posts_plant_plants', type_='foreignkey')
        batch_op.drop_constraint('fk_posts_user_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_plant_id_plants'), 'plants', ['plant_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('user')
        batch_op.drop_column('plant')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_posts_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_posts_plant_id_plants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_user_users', 'users', ['user'], ['id'])
        batch_op.create_foreign_key('fk_posts_plant_plants', 'plants', ['plant'], ['id'])
        batch_op.drop_column('plant_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
