"""common name instead of id

Revision ID: ad38111d6a25
Revises: a16685ab6b95
Create Date: 2023-09-26 10:00:20.989410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad38111d6a25'
down_revision = 'a16685ab6b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_user_plant_plant_id_plants', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_plant_plant_plants'), 'plants', ['plant'], ['common_name'])
        batch_op.drop_column('plant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_plant_plant_plants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_plant_plant_id_plants', 'plants', ['plant_id'], ['id'])
        batch_op.drop_column('plant')

    # ### end Alembic commands ###
