"""testing relationship

Revision ID: b920ea9ccf51
Revises: 749e343bce7a
Create Date: 2023-09-23 09:52:33.665349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b920ea9ccf51'
down_revision = '749e343bce7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('plant',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint('fk_posts_plant_plants', type_='foreignkey')
        batch_op.drop_constraint('fk_posts_user_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_plant_plants'), 'plants', ['plant'], ['common_name'])
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_users'), 'users', ['user'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_user_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_posts_plant_plants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_user_users', 'users', ['user'], ['id'])
        batch_op.create_foreign_key('fk_posts_plant_plants', 'plants', ['plant'], ['id'])
        batch_op.alter_column('plant',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('user',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
