"""added plant and post relationship

Revision ID: bc1f333c99be
Revises: 8952155a301f
Create Date: 2023-09-22 18:01:17.990573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1f333c99be'
down_revision = '8952155a301f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_posts_plant_id_plants'), 'plants', ['plant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_plant_id_plants'), type_='foreignkey')
        batch_op.drop_column('plant_id')

    # ### end Alembic commands ###
