"""added plant and post relationship

Revision ID: dc12d1f29481
Revises: bc1f333c99be
Create Date: 2023-09-22 18:06:13.552169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc12d1f29481'
down_revision = 'bc1f333c99be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint('fk_posts_plant_id_plants', type_='foreignkey')
        batch_op.drop_constraint('fk_posts_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_plant_id_plants'), 'plants', ['plant_id'], ['common_name'])
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_id_users'), 'users', ['user_id'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_posts_plant_id_plants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_posts_plant_id_plants', 'plants', ['plant_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
